const pokemony = [
	{
		id: 1,
		nazwa: 'Bulbasaur',
		numer: '#001',
		typy: ['grass', 'poison'],
		opis: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
		wzrost: '0.7 m',
		waga: '6.9 kg',
		zdjecie: 'img/1.png',
		ewolucja: 'Bulbasaur → Ivysaur → Venusaur',
		zdolnosci: ['Overgrow', 'Chlorophyll'],
	},
	{
		id: 2,
		nazwa: 'Ivysaur',
		numer: '#002',
		typy: ['grass', 'poison'],
		opis: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.',
		wzrost: '1.0 m',
		waga: '13.0 kg',
		zdjecie: 'img/2.png',
		ewolucja: 'Bulbasaur → Ivysaur → Venusaur',
		zdolnosci: ['Overgrow', 'Chlorophyll'],
	},
	{
		id: 3,
		nazwa: 'Venusaur',
		numer: '#003',
		typy: ['grass', 'poison'],
		opis: 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.',
		wzrost: '2.0 m',
		waga: '100.0 kg',
		zdjecie: 'img/3.png',
		ewolucja: 'Bulbasaur → Ivysaur → Venusaur',
		zdolnosci: ['Overgrow', 'Chlorophyll'],
	},
	{
		id: 69,
		nazwa: 'Bellsprout',
		numer: '#069',
		typy: ['grass', 'poison'],
		opis: 'A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture.',
		wzrost: '0.7 m',
		waga: '4.0 kg',
		zdjecie: 'img/69.png',
		ewolucja: 'Bellsprout → Weepinbell → Victreebel',
		zdolnosci: ['Chlorophyll', 'Gluttony'],
	},
	{
		id: 70,
		nazwa: 'Weepinbell',
		numer: '#070',
		typy: ['grass', 'poison'],
		opis: 'It spits out Poison Powder to immobilize the enemy and then finishes it with a spray of Acid.',
		wzrost: '1.0 m',
		waga: '6.4 kg',
		zdjecie: 'img/70.png',
		ewolucja: 'Bellsprout → Weepinbell → Victreebel',
		zdolnosci: ['Chlorophyll', 'Gluttony'],
	},
	{
		id: 71,
		nazwa: 'Victreebel',
		numer: '#071',
		typy: ['grass', 'poison'],
		opis: 'Said to live in huge colonies deep in jungles, although no one has ever returned from there.',
		wzrost: '1.7 m',
		waga: '15.5 kg',
		zdjecie: 'img/71.png',
		ewolucja: 'Bellsprout → Weepinbell → Victreebel',
		zdolnosci: ['Chlorophyll', 'Gluttony'],
	},
	{
		id: 92,
		nazwa: 'Gastly',
		numer: '#092',
		typy: ['ghost', 'poison'],
		opis: 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.',
		wzrost: '1.3 m',
		waga: '0.1 kg',
		zdjecie: 'img/92.png',
		ewolucja: 'Gastly → Haunter → Gengar',
		zdolnosci: ['Levitate'],
	},
	{
		id: 93,
		nazwa: 'Haunter',
		numer: '#093',
		typy: ['ghost', 'poison'],
		opis: 'Because of its ability to slip through block walls, it is said to be from another dimension.',
		wzrost: '1.6 m',
		waga: '0.1 kg',
		zdjecie: 'img/93.png',
		ewolucja: 'Gastly → Haunter → Gengar',
		zdolnosci: ['Levitate'],
	},
	{
		id: 94,
		nazwa: 'Gengar',
		numer: '#094',
		typy: ['ghost', 'poison'],
		opis: 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.',
		wzrost: '1.5 m',
		waga: '40.5 kg',
		zdjecie: 'img/94.png',
		ewolucja: 'Gastly → Haunter → Gengar',
		zdolnosci: ['Cursed Body'],
	},
	{
		id: 9400,
		nazwa: 'Gengar (Galar)',
		numer: '#094G',
		typy: ['ghost', 'poison'],
		opis: 'This Gengar has been in contact with Gigantamax energy and takes on a new fearsome form in the Galar region.',
		wzrost: '1.5 m',
		waga: '40.5 kg',
		zdjecie: 'img/94.png',
		ewolucja: 'Gastly → Haunter → Gengar (Galar)',
		zdolnosci: ['Cursed Body', 'Perish Body'],
		galar: true,
	},
	{
		id: 143,
		nazwa: 'Snorlax',
		numer: '#143',
		typy: ['normal'],
		opis: 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.',
		wzrost: '2.1 m',
		waga: '460.0 kg',
		zdjecie: 'img/143.png',
		ewolucja: 'Munchlax → Snorlax',
		zdolnosci: ['Immunity', 'Thick Fat', 'Gluttony'],
	},
	{
		id: 145,
		nazwa: 'Zapdos',
		numer: '#145',
		typy: ['electric', 'flying'],
		opis: 'A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.',
		wzrost: '1.6 m',
		waga: '52.6 kg',
		zdjecie: 'img/145.png',
		ewolucja: 'Nie ewoluuje',
		zdolnosci: ['Pressure', 'Static'],
	},
	{
		id: 179,
		nazwa: 'Mareep',
		numer: '#179',
		typy: ['electric'],
		opis: 'If static electricity builds in its body, its fleece doubles in volume. Touching it will shock you.',
		wzrost: '0.6 m',
		waga: '7.8 kg',
		zdjecie: 'img/179.png',
		ewolucja: 'Mareep → Flaaffy → Ampharos',
		zdolnosci: ['Static', 'Plus'],
	},
	{
		id: 180,
		nazwa: 'Flaaffy',
		numer: '#180',
		typy: ['electric'],
		opis: "As a result of storing too much electricity, it developed patches where even downy wool won't grow.",
		wzrost: '0.8 m',
		waga: '13.3 kg',
		zdjecie: 'img/180.png',
		ewolucja: 'Mareep → Flaaffy → Ampharos',
		zdolnosci: ['Static', 'Plus'],
	},
	{
		id: 181,
		nazwa: 'Ampharos',
		numer: '#181',
		typy: ['electric'],
		opis: 'The tip of its tail glows brightly and can be seen far away. It acts as a beacon for lost people.',
		wzrost: '1.4 m',
		waga: '61.5 kg',
		zdjecie: 'img/181.png',
		ewolucja: 'Mareep → Flaaffy → Ampharos',
		zdolnosci: ['Static', 'Plus'],
	},
	{
		id: 246,
		nazwa: 'Larvitar',
		numer: '#246',
		typy: ['rock', 'ground'],
		opis: 'Born deep underground, this Pokémon feeds on soil. It has to consume a mountain worth of dirt before it can emerge.',
		wzrost: '0.6 m',
		waga: '72.0 kg',
		zdjecie: 'img/246.png',
		ewolucja: 'Larvitar → Pupitar → Tyranitar',
		zdolnosci: ['Guts', 'Sand Veil'],
	},
	{
		id: 247,
		nazwa: 'Pupitar',
		numer: '#247',
		typy: ['rock', 'ground'],
		opis: 'Even sealed in its shell, it can move freely. Hard and fast, it will not stop attacking until its enemy falls.',
		wzrost: '1.2 m',
		waga: '152.0 kg',
		zdjecie: 'img/247.png',
		ewolucja: 'Larvitar → Pupitar → Tyranitar',
		zdolnosci: ['Shed Skin'],
	},
	{
		id: 248,
		nazwa: 'Tyranitar',
		numer: '#248',
		typy: ['rock', 'dark'],
		opis: "Its body can't be harmed by any sort of attack, so it is very eager to make enemies. It topples mountains and buries rivers.",
		wzrost: '2.0 m',
		waga: '202.0 kg',
		zdjecie: 'img/248.png',
		ewolucja: 'Larvitar → Pupitar → Tyranitar',
		zdolnosci: ['Sand Stream', 'Unnerve'],
	},
	{
		id: 446,
		nazwa: 'Munchlax',
		numer: '#446',
		typy: ['normal'],
		opis: 'It wolfs down its own weight in food once a day. It swallows food whole with almost no chewing.',
		wzrost: '0.6 m',
		waga: '105.0 kg',
		zdjecie: 'img/446.png',
		ewolucja: 'Munchlax → Snorlax',
		zdolnosci: ['Pickup', 'Thick Fat', 'Gluttony'],
	},
	{
		id: 4,
		nazwa: 'Charmander',
		numer: '#004',
		typy: ['fire'],
		opis: "The flame on its tail indicates Charmander's life force. If it goes out, the Pokémon dies.",
		wzrost: '0.6 m',
		waga: '8.5 kg',
		zdjecie: 'img/4.png',
		ewolucja: 'Charmander → Charmeleon → Charizard',
		zdolnosci: ['Blaze', 'Solar Power'],
	},
	{
		id: 5,
		nazwa: 'Charmeleon',
		numer: '#005',
		typy: ['fire'],
		opis: 'It has a barbaric nature. In battle, it whips its fiery tail around and slashes with sharp claws.',
		wzrost: '1.1 m',
		waga: '19.0 kg',
		zdjecie: 'img/5.png',
		ewolucja: 'Charmander → Charmeleon → Charizard',
		zdolnosci: ['Blaze', 'Solar Power'],
	},
	{
		id: 6,
		nazwa: 'Charizard',
		numer: '#006',
		typy: ['fire', 'flying'],
		opis: 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.',
		wzrost: '1.7 m',
		waga: '90.5 kg',
		zdjecie: 'img/6.png',
		ewolucja: 'Charmander → Charmeleon → Charizard',
		zdolnosci: ['Blaze', 'Solar Power'],
	},
	{
		id: 7,
		nazwa: 'Squirtle',
		numer: '#007',
		typy: ['water'],
		opis: 'It shelters itself in its shell, then strikes back with spouts of water at every opportunity.',
		wzrost: '0.5 m',
		waga: '9.0 kg',
		zdjecie: 'img/7.png',
		ewolucja: 'Squirtle → Wartortle → Blastoise',
		zdolnosci: ['Torrent', 'Rain Dish'],
	},
	{
		id: 8,
		nazwa: 'Wartortle',
		numer: '#008',
		typy: ['water'],
		opis: 'It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.',
		wzrost: '1.0 m',
		waga: '22.5 kg',
		zdjecie: 'img/8.png',
		ewolucja: 'Squirtle → Wartortle → Blastoise',
		zdolnosci: ['Torrent', 'Rain Dish'],
	},
	{
		id: 9,
		nazwa: 'Blastoise',
		numer: '#009',
		typy: ['water'],
		opis: 'The jets of water it spouts from the rocket cannons on its shell can punch through thick steel.',
		wzrost: '1.6 m',
		waga: '85.5 kg',
		zdjecie: 'img/9.png',
		ewolucja: 'Squirtle → Wartortle → Blastoise',
		zdolnosci: ['Torrent', 'Rain Dish'],
	},
	{
		id: 25,
		nazwa: 'Pikachu',
		numer: '#025',
		typy: ['electric'],
		opis: 'It stores electricity in its electric sacs. When released at once, it can shock even strong opponents.',
		wzrost: '0.4 m',
		waga: '6.0 kg',
		zdjecie: 'img/25.png',
		ewolucja: 'Pichu → Pikachu → Raichu',
		zdolnosci: ['Static', 'Lightning Rod'],
	},
	{
		id: 26,
		nazwa: 'Raichu',
		numer: '#026',
		typy: ['electric'],
		opis: 'Its tail discharges electricity into the ground, protecting it from getting shocked itself.',
		wzrost: '0.8 m',
		waga: '30.0 kg',
		zdjecie: 'img/26.png',
		ewolucja: 'Pichu → Pikachu → Raichu',
		zdolnosci: ['Static', 'Lightning Rod'],
	},
	{
		id: 39,
		nazwa: 'Jigglypuff',
		numer: '#039',
		typy: ['normal', 'fairy'],
		opis: 'It captivates foes with its huge, round eyes, then lulls them to sleep by singing a soothing melody.',
		wzrost: '0.5 m',
		waga: '5.5 kg',
		zdjecie: 'img/39.png',
		ewolucja: 'Igglybuff → Jigglypuff → Wigglytuff',
		zdolnosci: ['Cute Charm', 'Competitive', 'Friend Guard'],
	},
	{
		id: 52,
		nazwa: 'Meowth',
		numer: '#052',
		typy: ['normal'],
		opis: 'It is a nocturnal Pokémon that loves round objects. It is said to bring good luck if found.',
		wzrost: '0.4 m',
		waga: '4.2 kg',
		zdjecie: 'img/52.png',
		ewolucja: 'Meowth → Persian',
		zdolnosci: ['Pickup', 'Technician', 'Unnerve'],
	},
	{
		id: 54,
		nazwa: 'Psyduck',
		numer: '#054',
		typy: ['water'],
		opis: 'It is constantly troubled by a headache. When its headache gets intense, it begins using strange powers.',
		wzrost: '0.8 m',
		waga: '19.6 kg',
		zdjecie: 'img/54.png',
		ewolucja: 'Psyduck → Golduck',
		zdolnosci: ['Damp', 'Cloud Nine', 'Swift Swim'],
	},
	{
		id: 58,
		nazwa: 'Growlithe',
		numer: '#058',
		typy: ['fire'],
		opis: 'Very loyal to its Trainer. It will bark at anything it perceives as a threat, no matter how strong.',
		wzrost: '0.7 m',
		waga: '19.0 kg',
		zdjecie: 'img/58.png',
		ewolucja: 'Growlithe → Arcanine',
		zdolnosci: ['Intimidate', 'Flash Fire', 'Justified'],
	},
	{
		id: 59,
		nazwa: 'Arcanine',
		numer: '#059',
		typy: ['fire'],
		opis: 'An ancient picture scroll shows that people were captivated by its movement as it gallops through prairies.',
		wzrost: '1.9 m',
		waga: '155.0 kg',
		zdjecie: 'img/59.png',
		ewolucja: 'Growlithe → Arcanine',
		zdolnosci: ['Intimidate', 'Flash Fire', 'Justified'],
	},
	{
		id: 66,
		nazwa: 'Machop',
		numer: '#066',
		typy: ['fighting'],
		opis: "Its whole body is composed of muscles. Even though it's the size of a human child, it can hurl 100 adults.",
		wzrost: '0.8 m',
		waga: '19.5 kg',
		zdjecie: 'img/66.png',
		ewolucja: 'Machop → Machoke → Machamp',
		zdolnosci: ['Guts', 'No Guard', 'Steadfast'],
	},
	{
		id: 67,
		nazwa: 'Machoke',
		numer: '#067',
		typy: ['fighting'],
		opis: 'It happily carries heavy cargo to toughen up. It willingly does hard work for people.',
		wzrost: '1.5 m',
		waga: '70.5 kg',
		zdjecie: 'img/67.png',
		ewolucja: 'Machop → Machoke → Machamp',
		zdolnosci: ['Guts', 'No Guard', 'Steadfast'],
	},
	{
		id: 68,
		nazwa: 'Machamp',
		numer: '#068',
		typy: ['fighting'],
		opis: 'It punches with its four arms at blinding speed. It can launch 1,000 punches in two seconds.',
		wzrost: '1.6 m',
		waga: '130.0 kg',
		zdjecie: 'img/68.png',
		ewolucja: 'Machop → Machoke → Machamp',
		zdolnosci: ['Guts', 'No Guard', 'Steadfast'],
	},
	{
		id: 74,
		nazwa: 'Geodude',
		numer: '#074',
		typy: ['rock', 'ground'],
		opis: 'It climbs mountain paths using its arms. It is very dangerous when angered—it throws rocks.',
		wzrost: '0.4 m',
		waga: '20.0 kg',
		zdjecie: 'img/74.png',
		ewolucja: 'Geodude → Graveler → Golem',
		zdolnosci: ['Rock Head', 'Sturdy', 'Sand Veil'],
	},
	{
		id: 75,
		nazwa: 'Graveler',
		numer: '#075',
		typy: ['rock', 'ground'],
		opis: 'It rolls down mountains to crush anything in its path. It can even stop a train by doing so.',
		wzrost: '1.0 m',
		waga: '105.0 kg',
		zdjecie: 'img/75.png',
		ewolucja: 'Geodude → Graveler → Golem',
		zdolnosci: ['Rock Head', 'Sturdy', 'Sand Veil'],
	},
	{
		id: 76,
		nazwa: 'Golem',
		numer: '#076',
		typy: ['rock', 'ground'],
		opis: 'It sheds its skin once a year. The shed shell then crumbles and returns to the soil.',
		wzrost: '1.4 m',
		waga: '300.0 kg',
		zdjecie: 'img/76.png',
		ewolucja: 'Geodude → Graveler → Golem',
		zdolnosci: ['Rock Head', 'Sturdy', 'Sand Veil'],
	},
	{
		id: 133,
		nazwa: 'Eevee',
		numer: '#133',
		typy: ['normal'],
		opis: 'Its genetic code is irregular. It may evolve in a variety of ways depending on its environment.',
		wzrost: '0.3 m',
		waga: '6.5 kg',
		zdjecie: 'img/133.png',
		ewolucja: 'Eevee → Vaporeon / Jolteon / Flareon / ...',
		zdolnosci: ['Run Away', 'Adaptability', 'Anticipation'],
	},
	{
		id: 134,
		nazwa: 'Vaporeon',
		numer: '#134',
		typy: ['water'],
		opis: 'Its cell composition is similar to water molecules. It melts into water to become invisible.',
		wzrost: '1.0 m',
		waga: '29.0 kg',
		zdjecie: 'img/134.png',
		ewolucja: 'Eevee → Vaporeon',
		zdolnosci: ['Water Absorb', 'Hydration'],
	},
	{
		id: 135,
		nazwa: 'Jolteon',
		numer: '#135',
		typy: ['electric'],
		opis: 'It can shoot bristles of fur that generate electricity. Its sensitive ears can hear a mile away.',
		wzrost: '0.8 m',
		waga: '24.5 kg',
		zdjecie: 'img/135.png',
		ewolucja: 'Eevee → Jolteon',
		zdolnosci: ['Volt Absorb', 'Quick Feet'],
	},
	{
		id: 136,
		nazwa: 'Flareon',
		numer: '#136',
		typy: ['fire'],
		opis: 'It stores some of the air it inhales in its internal flame sac, where it can reach 3,000 degrees Fahrenheit.',
		wzrost: '0.9 m',
		waga: '25.0 kg',
		zdjecie: 'img/136.png',
		ewolucja: 'Eevee → Flareon',
		zdolnosci: ['Flash Fire', 'Guts'],
	},
]

const cdnMap = {
	1: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
	2: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
	3: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
	69: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png',
	70: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png',
	71: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png',
	92: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png',
	93: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png',
	94: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
	9400: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
	143: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png',
	145: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png',
	179: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/179.png',
	180: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/180.png',
	181: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/181.png',
	246: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/246.png',
	247: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/247.png',
	248: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png',
	446: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/446.png',
	4: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
	5: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png',
	6: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
	7: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
	8: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png',
	9: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
	25: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
	26: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png',
	39: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png',
	52: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png',
	54: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png',
	58: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png',
	59: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png',
	66: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png',
	67: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png',
	68: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png',
	74: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png',
	75: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png',
	76: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png',
	133: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
	134: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png',
	135: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png',
	136: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png',
}

pokemony.forEach(p => {
	if (cdnMap[p.id]) {
		p.zdjecie = cdnMap[p.id]
	}
})